### ISSUE TITLE
CrOs ver 75

### ISSUE THREAD

**Issue by guywinters** [iamtheyammer/chromebook-enrollment-scripts#1]
This code worked great right up to the Enterprise Enrollment screen. The problem turned out to relate to the ToS() call in line 91; the Terms of Service process is already part of the wifiConfig() routine, at lines 241-252. Commenting out line 91 so ToS() is not called was a quick and effective fix, but it would be cleaner and more clear to remove the code from wifiConfig() and keep the ToS() call.

**Comment by iamtheyammer** [comment]
Did that PR fix the issue? I don't have a chromebook in front of me so I would be super grateful if you could test the code in that PR out. Thanks!

**Comment by guywinters** [comment]
Works perfectly, thanks!
